# The URL the site will be built for
# base_url = "http://127.0.0.1:1111" # ONLY FOR LOCAL TESTING
base_url = "https://hsg-methods-reading-group.github.io"

title = "St. Gallen Methods Reading Group"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
internal_level = "warn"

[extra]
author = ""
display_author = false

favicon = "favicon.ico"
image = ""

default_theme = "light"
list_pages = false
twitter_card = false

header_nav = [
  { url = "/past-editions", name = "Past Editions" },
  { url = "/about", name = "About" },
]
